notifications:
  email:
    on_success: never
    on_failure: always
    
language: go
go:
  - "1.10"

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
 - sh coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
